"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import IprCertificateUploader from "@/components/IprCertificateUploader";

import { getContinuationRouteFromCertificate } from "@/lib/ipr-phase-map";

import type { AcceptedIprCertificateUpload } from "@/components/IprCertificateUploader";

const CONTINUATION_RULES = [
  {
    title: "Upload the latest HBCE-IPR certificate",
    text:
      "Use the most recent `.hbce.json` file generated by the app. The system reads the certificate phase and determines the next required onboarding step."
  },
  {
    title: "Do not upload personal documents here",
    text:
      "CIE, driving licence, passport, tessera sanitaria, codice fiscale, selfie and video are uploaded only inside their specific onboarding phases."
  },
  {
    title: "Fail closed by default",
    text:
      "If the uploaded certificate has an invalid protocol, issuer, phase, next phase or payload hash, the app rejects it and does not continue."
  }
] as const;

const CERTIFICATE_CHAIN = [
  {
    code: "01",
    title: "Subject Created",
    route: "/onboarding/phase-1",
    description:
      "Creates the initial HBCE IPR subject after email OTP and phone SMS OTP verification."
  },
  {
    code: "02",
    title: "Fiscal Identity",
    route: "/onboarding/phase-2",
    description:
      "Links the subject to a fiscal or national tax identifier and fiscal evidence hashes."
  },
  {
    code: "03",
    title: "Official ID Document",
    route: "/onboarding/phase-3",
    description:
      "Records official document metadata and protected document evidence hashes."
  },
  {
    code: "04",
    title: "Photo / Video Liveness",
    route: "/onboarding/photo-video",
    description:
      "Prepares face, selfie, liveness video references, physical descriptors and liveness state."
  },
  {
    code: "05",
    title: "Privacy & Compliance",
    route: "/onboarding/phase-5",
    description:
      "Records privacy, compliance, biometric/liveness consent and JOKER-C2 custody acknowledgement."
  },
  {
    code: "06",
    title: "Review Pending",
    route: "/onboarding/review",
    description:
      "Submits the onboarding package for HBCE review without approving IPR or access."
  },
  {
    code: "07",
    title: "IPR Approved",
    route: "/admin/review",
    description:
      "Admin/backend approval phase. This is not self-approved by the subject."
  },
  {
    code: "08",
    title: "IPR Card Issued",
    route: "/ipr-card",
    description:
      "Issues the IPR Card only after the approved HBCE review certificate."
  },
  {
    code: "09",
    title: "HBCE Operational Certificate",
    route: "/certificate",
    description:
      "Activates the operational certificate required before governed JOKER-C2 access."
  }
] as const;

const POSITIONING_POINTS = [
  {
    title: "Not a simple AI login",
    text:
      "Classic AI access is usually email, password, subscription and direct model access. HBCE requires operational identity onboarding before governed runtime access."
  },
  {
    title: "IPR before JOKER-C2",
    text:
      "JOKER-C2 is not opened by a normal account. It is accessed through an IPR-verified operational certificate chain."
  },
  {
    title: "Hash-only public verification",
    text:
      "Portable certificates can contain private fields. Public verification must expose minimized hash-only references."
  },
  {
    title: "No raw biometric media in portable files",
    text:
      "Raw photos, raw videos, face templates and biometric templates must remain outside portable certificates and public routes."
  }
] as const;

const SECURITY_BOUNDARIES = [
  "No verified IPR, no governed JOKER-C2 access.",
  "One certificate unlocks only the next required phase.",
  "The latest valid `.hbce.json` certificate is the continuation key.",
  "Invalid protocol, issuer, phase or payload hash blocks continuation.",
  "Official documents are uploaded only in the official document phase.",
  "Fiscal documents are uploaded only in the fiscal identity phase.",
  "Photo, selfie and video liveness references are handled only in the liveness phase.",
  "The onboarding page is a continuation gateway, not a document intake page.",
  "IPR does not replace CIE, SPID, EUDI Wallet, passport or official state identity.",
  "JOKER-C2 access remains denied until the operational certificate is valid."
] as const;

function getSafeNextPhase(upload: AcceptedIprCertificateUpload): string {
  return upload.certificate.next.next_phase ?? "NO_NEXT_PHASE";
}

function getSafePreviousPayloadSha256(
  upload: AcceptedIprCertificateUpload
): string {
  return upload.previousPayloadSha256 ?? "ROOT_CERTIFICATE";
}

export default function OnboardingPage() {
  const router = useRouter();

  const [acceptedUpload, setAcceptedUpload] =
    useState<AcceptedIprCertificateUpload | null>(null);

  const continuationRoute = useMemo(() => {
    if (!acceptedUpload) {
      return null;
    }

    return getContinuationRouteFromCertificate(acceptedUpload.certificate);
  }, [acceptedUpload]);

  function continueFromCertificate(): void {
    if (!continuationRoute) {
      return;
    }

    router.push(continuationRoute);
  }

  return (
    <div className="hbce-container">
      <section className="hbce-hero">
        <p className="hbce-kicker">HBCE IPR Onboarding App</p>

        <h1 className="hbce-title">
          Start or continue the HBCE-IPR operational identity chain.
        </h1>

        <p className="hbce-lead">
          This is the operational onboarding gateway for progressive HBCE-IPR
          certificate release. The subject starts with verified contact data,
          generates a private portable certificate, uploads that certificate in
          the next phase and continues until the final operational certificate
          enables governed JOKER-C2 access.
        </p>

        <div className="hbce-actions">
          <Link
            className="hbce-btn hbce-btn--primary"
            href="/onboarding/phase-1"
          >
            Start New IPR
          </Link>

          <a className="hbce-btn" href="#continue-ipr">
            Continue Existing IPR
          </a>

          <Link className="hbce-btn" href="/access/joker-c2">
            Access JOKER-C2
          </Link>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card hbce-card--soft">
            <p className="hbce-kicker">Core rule</p>
            <h2>No verified IPR, no governed JOKER-C2 access.</h2>

            <p>
              HBCE does not treat JOKER-C2 as a generic AI page opened by email
              and password. Access is governed by the certificate chain:
              subject creation, fiscal identity, official document, liveness,
              privacy, review, approval, IPR Card and operational certificate.
            </p>
          </div>

          <div className="hbce-card hbce-card--danger">
            <p className="hbce-kicker">Access boundary</p>
            <h2>The onboarding gateway is not the runtime.</h2>

            <p>
              This page starts or resumes the onboarding sequence. It does not
              approve IPR, does not issue an IPR Card, does not activate the
              operational certificate and does not grant JOKER-C2 access by
              itself.
            </p>
          </div>
        </div>
      </section>

      <section className="hbce-section" id="continue-ipr">
        <IprCertificateUploader
          mode="read_any"
          required={false}
          title="Continue with Existing HBCE IPR Certificate"
          description="Upload the latest HBCE-IPR `.hbce.json` certificate you own. The app will read the chain state and open the next required phase."
          onCertificateAccepted={(upload) => {
            setAcceptedUpload(upload);
          }}
          onValidation={(validation) => {
            if (!validation.valid) {
              setAcceptedUpload(null);
            }
          }}
        />

        {acceptedUpload ? (
          <div className="hbce-card hbce-card--success">
            <p className="hbce-kicker">Continuation ready</p>

            <h2>Certificate accepted.</h2>

            <p>
              The uploaded HBCE-IPR certificate is valid. Continue to the next
              required onboarding phase. If no continuation route is available,
              the chain has either reached a terminal state or the phase map
              must be updated.
            </p>

            <div className="hbce-card-preview__meta">
              <div className="hbce-meta">
                <span className="hbce-meta__label">current_phase</span>
                <span className="hbce-meta__value hbce-mono">
                  {acceptedUpload.certificate.phase.code}
                </span>
              </div>

              <div className="hbce-meta">
                <span className="hbce-meta__label">next_phase</span>
                <span className="hbce-meta__value hbce-mono">
                  {getSafeNextPhase(acceptedUpload)}
                </span>
              </div>

              <div className="hbce-meta">
                <span className="hbce-meta__label">payload_sha256</span>
                <span className="hbce-meta__value hbce-mono">
                  {acceptedUpload.payloadSha256}
                </span>
              </div>

              <div className="hbce-meta">
                <span className="hbce-meta__label">
                  previous_payload_sha256
                </span>
                <span className="hbce-meta__value hbce-mono">
                  {getSafePreviousPayloadSha256(acceptedUpload)}
                </span>
              </div>

              <div className="hbce-meta">
                <span className="hbce-meta__label">continuation_route</span>
                <span className="hbce-meta__value hbce-mono">
                  {continuationRoute ?? "NO_ROUTE_AVAILABLE"}
                </span>
              </div>
            </div>

            <div className="hbce-actions">
              <button
                className="hbce-btn hbce-btn--primary"
                disabled={!continuationRoute}
                type="button"
                onClick={continueFromCertificate}
              >
                Continue to next phase
              </button>
            </div>
          </div>
        ) : null}
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--3">
          {CONTINUATION_RULES.map((rule) => (
            <article className="hbce-card" key={rule.title}>
              <h2>{rule.title}</h2>
              <p>{rule.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card">
          <p className="hbce-kicker">Certificate chain</p>

          <h2>Canonical HBCE-IPR progression</h2>

          <p>
            The onboarding app must not behave as a static brochure or a simple
            registration page. It behaves as a progressive certificate chain
            where each file becomes the input key for the next controlled step.
          </p>

          <div className="hbce-grid hbce-grid--3">
            {CERTIFICATE_CHAIN.map((item) => (
              <article className="hbce-card hbce-card--soft" key={item.code}>
                <p className="hbce-kicker">Certificate {item.code}</p>
                <h2>{item.title}</h2>
                <p>{item.description}</p>

                <div className="hbce-actions">
                  <Link className="hbce-btn" href={item.route}>
                    Open phase
                  </Link>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card">
            <p className="hbce-kicker">Operational positioning</p>

            <h2>HBCE onboarding is closer to banking intake than AI signup.</h2>

            <p>
              A generic AI signup starts with an email and ends with model
              access. HBCE starts with verified contact creation and proceeds
              through fiscal identity, official document evidence, liveness,
              compliance, review and certificate issuance before JOKER-C2 can be
              opened.
            </p>

            <ul className="hbce-list">
              {POSITIONING_POINTS.map((point) => (
                <li key={point.title}>
                  <strong>{point.title}:</strong> {point.text}
                </li>
              ))}
            </ul>
          </div>

          <div className="hbce-card hbce-card--danger">
            <p className="hbce-kicker">Document boundary</p>

            <h2>Personal documents are not uploaded on this page.</h2>

            <p>
              CIE, patente, passaporto, tessera sanitaria, codice fiscale,
              selfie and video verification are phase-specific evidence. They
              must be uploaded only inside the correct phase and represented in
              the portable certificate as hashes, references and states, not raw
              files.
            </p>

            <ul className="hbce-list">
              {SECURITY_BOUNDARIES.map((boundary) => (
                <li key={boundary}>{boundary}</li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card hbce-card--soft">
          <p className="hbce-kicker">Final access logic</p>

          <h2>JOKER-C2 opens only after the operational certificate.</h2>

          <p>
            The IPR Card is the operational key and the HBCE Operational
            Certificate is the access condition. Until the chain reaches that
            state, JOKER-C2 access remains denied by design.
          </p>

          <div className="hbce-actions">
            <Link className="hbce-btn hbce-btn--primary" href="/certificate">
              Generate Operational Certificate
            </Link>

            <Link className="hbce-btn" href="/access/joker-c2">
              Test JOKER-C2 Access Gate
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
