"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import IprCertificateUploader from "@/components/IprCertificateUploader";

import { getContinuationRouteFromCertificate } from "@/lib/ipr-phase-map";

import type {
  AcceptedIprCertificateUpload
} from "@/components/IprCertificateUploader";

const CONTINUATION_RULES = [
  {
    title: "Upload the latest HBCE-IPR certificate",
    text:
      "Use the most recent `.hbce.json` file generated by the app. The system reads the certificate phase and determines the next required step."
  },
  {
    title: "Do not upload personal documents here",
    text:
      "CIE, driving licence, passport, tessera sanitaria, codice fiscale, selfie and video are uploaded only inside their specific onboarding phases."
  },
  {
    title: "Fail closed by default",
    text:
      "If the uploaded certificate has an invalid protocol, issuer, phase or payload hash, the app rejects it and does not continue."
  }
] as const;

const CERTIFICATE_CHAIN = [
  "01 — Subject Created",
  "02 — Fiscal Identity",
  "03 — Official ID Document",
  "04 — Liveness Check",
  "05 — Privacy & Compliance",
  "06 — Review Pending",
  "07 — IPR Approved",
  "08 — IPR Card Issued",
  "09 — HBCE Operational Certificate"
] as const;

export default function OnboardingPage() {
  const router = useRouter();

  const [acceptedUpload, setAcceptedUpload] =
    useState<AcceptedIprCertificateUpload | null>(null);

  const continuationRoute = useMemo(() => {
    if (!acceptedUpload) {
      return null;
    }

    return getContinuationRouteFromCertificate(acceptedUpload.certificate);
  }, [acceptedUpload]);

  function continueFromCertificate() {
    if (!continuationRoute) {
      return;
    }

    router.push(continuationRoute);
  }

  return (
    <div className="hbce-container">
      <section className="hbce-hero">
        <p className="hbce-kicker">HBCE IPR Onboarding App</p>

        <h1 className="hbce-title">
          Start or continue the HBCE-IPR certificate chain.
        </h1>

        <p className="hbce-lead">
          This is the operational onboarding gateway for progressive HBCE-IPR
          certificate release. The user starts with basic subject data, receives
          a downloadable certificate, uploads that certificate in the next phase
          and continues until the final operational certificate enables governed
          JOKER-C2 access.
        </p>

        <div className="hbce-actions">
          <Link
            className="hbce-btn hbce-btn--primary"
            href="/onboarding/phase-1"
          >
            Start New IPR
          </Link>

          <Link className="hbce-btn" href="/access/joker-c2">
            Access JOKER-C2
          </Link>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card hbce-card--soft">
          <p className="hbce-kicker">Core rule</p>
          <h2>One certificate unlocks the next phase.</h2>
          <p>
            Every phase generates a downloadable HBCE-IPR certificate. Every
            next phase requires the previous certificate. The app verifies
            protocol, issuer, phase, next phase and payload hash before allowing
            continuation.
          </p>
        </div>
      </section>

      <section className="hbce-section">
        <IprCertificateUploader
          mode="read_any"
          required={false}
          title="Continue with Existing HBCE IPR Certificate"
          description="Upload the latest HBCE-IPR `.hbce.json` certificate you own. The app will read the chain state and open the next required phase."
          onCertificateAccepted={(upload) => {
            setAcceptedUpload(upload);
          }}
          onValidation={(validation) => {
            if (!validation.valid) {
              setAcceptedUpload(null);
            }
          }}
        />

        {acceptedUpload ? (
          <div className="hbce-card hbce-card--success">
            <p className="hbce-kicker">Continuation ready</p>

            <h2>Certificate accepted.</h2>

            <p>
              The uploaded HBCE-IPR certificate is valid. Continue to the next
              required onboarding phase.
            </p>

            <p className="hbce-mono">
              current_phase: {acceptedUpload.certificate.phase.code}
            </p>

            <p className="hbce-mono">
              next_phase: {acceptedUpload.certificate.next.next_phase}
            </p>

            <p className="hbce-mono">
              payload_sha256: {acceptedUpload.payloadSha256}
            </p>

            {acceptedUpload.previousPayloadSha256 ? (
              <p className="hbce-mono">
                previous_payload_sha256:{" "}
                {acceptedUpload.previousPayloadSha256}
              </p>
            ) : null}

            <div className="hbce-actions">
              <button
                className="hbce-btn hbce-btn--primary"
                type="button"
                onClick={continueFromCertificate}
              >
                Continue to next phase
              </button>
            </div>
          </div>
        ) : null}
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--3">
          {CONTINUATION_RULES.map((rule) => (
            <article className="hbce-card" key={rule.title}>
              <h2>{rule.title}</h2>
              <p>{rule.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card">
          <p className="hbce-kicker">Certificate chain</p>

          <h2>Canonical HBCE-IPR progression</h2>

          <p>
            The onboarding app must not behave as a simple registration page. It
            must behave as a progressive certificate chain where each file
            becomes the input key for the next step.
          </p>

          <ul className="hbce-list">
            {CERTIFICATE_CHAIN.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card">
            <p className="hbce-kicker">IPR upload point</p>

            <h2>Previous certificates are always uploaded here.</h2>

            <p>
              The same logical upload component is used across the app:
              onboarding continuation, phase validation, review, IPR Card
              issuance, operational certificate issuance and JOKER-C2 access.
            </p>
          </div>

          <div className="hbce-card hbce-card--danger">
            <p className="hbce-kicker">Document boundary</p>

            <h2>Personal documents are not uploaded on this page.</h2>

            <p>
              CIE, patente, passaporto, tessera sanitaria, codice fiscale,
              selfie and video verification are phase-specific evidence. They
              must be uploaded only inside the correct phase and represented in
              the portable certificate as hashes, not raw files.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
