"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import IprCertificateUploader from "@/components/IprCertificateUploader";

import { getContinuationRouteFromCertificate } from "@/lib/ipr-phase-map";

import type { AcceptedIprCertificateUpload } from "@/components/IprCertificateUploader";

const CERTIFICATE_CHAIN = [
  {
    title: "01 — Subject Created",
    text: "Email, phone, name, country and date of birth create the first HBCE-IPR certificate."
  },
  {
    title: "02 — Fiscal Identity",
    text: "Codice fiscale, tax ID, fiscal country and tessera sanitaria or equivalent fiscal evidence."
  },
  {
    title: "03 — Official ID Document",
    text: "CIE, driving licence, passport, EU identity card or another authorized official document."
  },
  {
    title: "04 — Liveness Check",
    text: "Selfie, video verification and operational declaration."
  },
  {
    title: "05 — Privacy & Compliance",
    text: "Privacy, hash-only logic, document authenticity and HBCE policy acceptance."
  },
  {
    title: "06 — Review Pending",
    text: "The onboarding package is submitted for HBCE review."
  },
  {
    title: "07 — IPR Approved",
    text: "HBCE approval certificate generated by admin/operator workflow."
  },
  {
    title: "08 — IPR Card",
    text: "Virtual IPR Card issued as internal HBCE operational identity key."
  },
  {
    title: "09 — Operational Certificate",
    text: "Final HBCE certificate with JOKER_C2_ACCESS scope."
  }
] as const;

const OPERATIONAL_BOUNDARIES = [
  "The app does not issue IBANs, bank accounts or electronic money.",
  "The app does not replace CIE, SPID, EUDI Wallet, passport or state identity.",
  "The portable certificate stores hashes and metadata, not raw documents.",
  "Real production verification requires backend, protected storage and server-side signing.",
  "JOKER-C2 access remains denied unless the final operational certificate is valid."
] as const;

export default function HomePage() {
  const router = useRouter();

  const [acceptedUpload, setAcceptedUpload] =
    useState<AcceptedIprCertificateUpload | null>(null);

  const continuationRoute = useMemo(() => {
    if (!acceptedUpload) {
      return null;
    }

    return getContinuationRouteFromCertificate(acceptedUpload.certificate);
  }, [acceptedUpload]);

  function continueFromCertificate() {
    if (!continuationRoute) {
      return;
    }

    router.push(continuationRoute);
  }

  return (
    <div className="hbce-container">
      <section className="hbce-hero">
        <p className="hbce-kicker">HBCE IPR Onboarding Gateway</p>

        <h1 className="hbce-title">
          Verify the subject before opening governed AI access.
        </h1>

        <p className="hbce-lead">
          HBCE IPR Onboarding App is the operational identity gateway for
          progressive HBCE-IPR certificate release, IPR Card issuance,
          operational certificate activation and governed JOKER-C2 access. An
          email is not enough. A subscription is not enough. Access to
          operational AI requires a verified operational identity chain.
        </p>

        <div className="hbce-actions">
          <Link
            className="hbce-btn hbce-btn--primary"
            href="/onboarding/phase-1"
          >
            Start New IPR
          </Link>

          <Link className="hbce-btn" href="/onboarding">
            Continue Onboarding
          </Link>

          <Link className="hbce-btn" href="/access/joker-c2">
            Access JOKER-C2
          </Link>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card hbce-card--soft">
          <p className="hbce-kicker">Core product rule</p>

          <h2>First verify who you are. Then access operational AI.</h2>

          <p>
            Classic AI access usually follows email, password, payment and model
            access. HBCE follows a different rule: subject onboarding, official
            evidence, fiscal identifier linkage, liveness check, review, IPR
            Card, operational certificate and only then JOKER-C2 access
            evaluation.
          </p>
        </div>
      </section>

      <section className="hbce-section">
        <IprCertificateUploader
          mode="read_any"
          required={false}
          title="Continue with Existing HBCE IPR Certificate"
          description="Upload the latest HBCE-IPR `.hbce.json` certificate generated by the app. The system reads the certificate phase and opens the next required step."
          onCertificateAccepted={(upload) => {
            setAcceptedUpload(upload);
          }}
          onValidation={(validation) => {
            if (!validation.valid) {
              setAcceptedUpload(null);
            }
          }}
        />

        {acceptedUpload ? (
          <div className="hbce-card hbce-card--success">
            <p className="hbce-kicker">Certificate accepted</p>

            <h2>Ready to continue the HBCE-IPR chain.</h2>

            <p>
              The uploaded certificate is valid. Continue to the next required
              onboarding phase.
            </p>

            <p className="hbce-mono">
              current_phase: {acceptedUpload.certificate.phase.code}
            </p>

            <p className="hbce-mono">
              next_phase: {acceptedUpload.certificate.next.next_phase}
            </p>

            <p className="hbce-mono">
              payload_sha256: {acceptedUpload.payloadSha256}
            </p>

            {acceptedUpload.previousPayloadSha256 ? (
              <p className="hbce-mono">
                previous_payload_sha256:{" "}
                {acceptedUpload.previousPayloadSha256}
              </p>
            ) : null}

            <div className="hbce-actions">
              <button
                className="hbce-btn hbce-btn--primary"
                type="button"
                onClick={continueFromCertificate}
              >
                Continue to next phase
              </button>
            </div>
          </div>
        ) : null}
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card">
            <p className="hbce-kicker">Classic AI model</p>

            <h2>Email, payment and model access.</h2>

            <p>
              Generic AI systems usually expose access after account creation,
              authentication and subscription. The access condition is mainly
              commercial or account-based.
            </p>

            <ul className="hbce-list">
              <li>Email registration</li>
              <li>Password or OAuth login</li>
              <li>Payment or subscription</li>
              <li>Direct access to the model</li>
            </ul>
          </div>

          <div className="hbce-card hbce-card--soft">
            <p className="hbce-kicker">HBCE model</p>

            <h2>Operational identity before governed AI.</h2>

            <p>
              HBCE separates ordinary login from operational authorization. The
              subject must produce a verifiable certificate chain before JOKER-C2
              can be opened.
            </p>

            <ul className="hbce-list">
              <li>Subject creation</li>
              <li>Fiscal identity evidence</li>
              <li>Official identity document evidence</li>
              <li>Selfie and video verification</li>
              <li>HBCE review</li>
              <li>IPR Card issuance</li>
              <li>Operational certificate</li>
              <li>JOKER-C2 certificate gate</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card">
          <p className="hbce-kicker">Certificate chain</p>

          <h2>Every certificate unlocks the next phase.</h2>

          <p>
            The app works through downloadable `.hbce.json` files. Each file
            contains the hash of the previous phase and the hash of its own
            canonical payload. The final certificate is the only file accepted by
            the JOKER-C2 access gate.
          </p>

          <div className="hbce-grid hbce-grid--3" style={{ marginTop: "18px" }}>
            {CERTIFICATE_CHAIN.map((step) => (
              <article className="hbce-card" key={step.title}>
                <h3>{step.title}</h3>
                <p>{step.text}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card">
            <p className="hbce-kicker">IPR upload rule</p>

            <h2>Certificates are uploaded in one logical point.</h2>

            <p>
              The HBCE-IPR certificate upload is always the same logical action:
              upload the previous `.hbce.json` certificate, validate it, then
              continue to the next phase. CIE, driving licence, passport,
              tessera sanitaria, selfie and video are phase-specific evidence,
              not continuation certificates.
            </p>
          </div>

          <div className="hbce-card hbce-card--danger">
            <p className="hbce-kicker">Fail-closed boundary</p>

            <h2>Invalid certificates do not continue.</h2>

            <p>
              Wrong protocol, wrong issuer, wrong phase, wrong next phase,
              missing previous hash, payload hash mismatch, inactive status or
              invalid scope blocks continuation and access.
            </p>
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card">
          <p className="hbce-kicker">Legal and operational boundary</p>

          <h2>IPR is an internal operational identity layer.</h2>

          <p>
            HBCE IPR is a verifiable operational identity layer linked to
            official evidence. It is not a state identity system and does not
            replace public identity documents or regulated trust services unless
            future integrations with recognized providers are formally
            activated.
          </p>

          <ul className="hbce-list">
            {OPERATIONAL_BOUNDARIES.map((boundary) => (
              <li key={boundary}>{boundary}</li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}
