import {
  PRIVACY_BOUNDARY_TEXT
} from "@/lib/constants";

import {
  BoundaryNotice
} from "@/components/BoundaryNotice";

import {
  OnboardingStartClient
} from "@/components/OnboardingStartClient";

import {
  OnboardingStepper
} from "@/components/OnboardingStepper";

import {
  StatusBadge
} from "@/components/StatusBadge";

const INITIAL_STATE_ITEMS = [
  {
    label:
      "Onboarding status",
    status:
      "started"
  },
  {
    label:
      "Email status",
    status:
      "pending"
  },
  {
    label:
      "IPR status",
    status:
      "not_created"
  },
  {
    label:
      "JOKER-C2 access",
    status:
      "denied"
  }
] as const;

const START_BOUNDARIES = [
  "This step creates the pseudonymous onboarding subject and STARTED session only after the server accepts the request.",
  "No identity data is collected by the start operation.",
  "No IPR is created at this stage.",
  "No IPR Card is issued at this stage.",
  "No operational certificate is active at this stage.",
  "JOKER-C2 access remains denied by default."
] as const;

export default function OnboardingStartPage() {
  return (
    <div className="hbce-container">
      <section className="hbce-hero">
        <p className="hbce-kicker">
          Step 01 · Start
        </p>

        <h1 className="hbce-title">
          Create the onboarding session.
        </h1>

        <p className="hbce-lead">
          Start creates only the initial
          pseudonymous HBCE onboarding state
          and its protected browser session.
          Identity and contact information
          belong to later authenticated
          stages. JOKER-C2 access remains
          denied.
        </p>
      </section>

      <section className="hbce-section">
        <div className="hbce-grid hbce-grid--2">
          <div className="hbce-card">
            <p className="hbce-kicker">
              Start boundary
            </p>

            <h2>
              Open the onboarding path
            </h2>

            <p>
              This operation sends only the
              acceptance of the onboarding
              terms and privacy boundary.
              Subject, onboarding and session
              identifiers are generated by
              the server and are not accepted
              from this page.
            </p>

            <OnboardingStartClient />
          </div>

          <div className="hbce-card hbce-card--soft">
            <p className="hbce-kicker">
              State after successful start
            </p>

            <h2>
              Registration is not
              authorization
            </h2>

            <p>
              These values describe the state
              expected only after the server
              has successfully created the
              onboarding session. They do not
              represent a verified IPR
              identity.
            </p>

            <div className="hbce-card-preview__meta">
              {INITIAL_STATE_ITEMS.map(
                (item) => (
                  <div
                    className="hbce-meta"
                    key={item.label}
                  >
                    <span className="hbce-meta__label">
                      {item.label}
                    </span>

                    <span className="hbce-meta__value">
                      <StatusBadge
                        status={
                          item.status
                        }
                      />
                    </span>
                  </div>
                )
              )}
            </div>

            <div className="hbce-divider" />

            <ul className="hbce-list">
              {START_BOUNDARIES.map(
                (boundary) => (
                  <li key={boundary}>
                    {boundary}
                  </li>
                )
              )}
            </ul>

            <div className="hbce-divider" />

            <BoundaryNotice
              title="Registration does not equal access"
            >
              Starting onboarding creates no
              JOKER-C2 authorization. Access
              remains denied until the later
              trust requirements are
              satisfied.
            </BoundaryNotice>
          </div>
        </div>
      </section>

      <section className="hbce-section">
        <div className="hbce-card">
          <h2>
            Current onboarding position
          </h2>

          <OnboardingStepper
            currentStep="start"
          />
        </div>
      </section>

      <section className="hbce-section">
        <BoundaryNotice
          title="Privacy boundary"
        >
          {PRIVACY_BOUNDARY_TEXT}
        </BoundaryNotice>
      </section>
    </div>
  );
}
